#ifndef CONFIG_BOARD_RESOURCES_H_
#define CONFIG_BOARD_RESOURCES_H_

/**
 * @file board_resources.h
 * @brief DEPRECATED — 使用 system/board/smartcar_board_resources.h。
 */

#include "system/board/smartcar_board_resources.h"

/* 向后兼容：旧枚举值 → 新枚举值 */
#define PAL_CH_MOTOR_R_FWD  SMARTCAR_PWM_MOTOR_R_FWD
#define PAL_CH_MOTOR_R_REV  SMARTCAR_PWM_MOTOR_R_REV
#define PAL_CH_MOTOR_L_FWD  SMARTCAR_PWM_MOTOR_L_FWD
#define PAL_CH_MOTOR_L_REV  SMARTCAR_PWM_MOTOR_L_REV
#define PAL_CH_SERVO        SMARTCAR_PWM_SERVO
#define PAL_PWM_ID_MAX      SMARTCAR_PWM_ID_MAX

#define PAL_PIN_BUZZER      SMARTCAR_GPIO_BUZZER
#define PAL_PIN_KEY1        SMARTCAR_GPIO_KEY1
#define PAL_PIN_KEY2        SMARTCAR_GPIO_KEY2
#define PAL_PIN_KEY3        SMARTCAR_GPIO_KEY3
#define PAL_PIN_KEY4        SMARTCAR_GPIO_KEY4
#define PAL_PIN_DIP1        SMARTCAR_GPIO_DIP1
#define PAL_PIN_DIP2        SMARTCAR_GPIO_DIP2
#define PAL_PIN_DIP3        SMARTCAR_GPIO_DIP3
#define PAL_PIN_DIP4        SMARTCAR_GPIO_DIP4
#define PAL_GPIO_ID_MAX     SMARTCAR_GPIO_ID_MAX

#define PAL_CH_ENCODER_L    SMARTCAR_ENCODER_LEFT
#define PAL_CH_ENCODER_R    SMARTCAR_ENCODER_RIGHT
#define PAL_ENCODER_ID_MAX  SMARTCAR_ENCODER_ID_MAX

#define PAL_CH_PIT_0        SMARTCAR_PIT_ENCODER_SAMPLE
#define PAL_CH_PIT_1        SMARTCAR_PIT_GYRO_TICK
#define PAL_CH_PIT_2        SMARTCAR_PIT_SPARE_2
#define PAL_CH_PIT_3        SMARTCAR_PIT_SPARE_3
#define PAL_PIT_ID_MAX      SMARTCAR_PIT_ID_MAX

#define PAL_CH_UART_CAM     SMARTCAR_UART_CAMERA
#define PAL_CH_UART_BT      SMARTCAR_UART_BT
#define PAL_UART_ID_MAX     SMARTCAR_UART_ID_MAX

#endif /* CONFIG_BOARD_RESOURCES_H_ */
